const data = [
  {
    product: "clothing",
    name: "Thread Collect",
    link: "https://threadcollect.com.au/",
    location: "City of Port Phillip and surrounding suburbs",
    drop_off: "Collection",
    notes: "market days",
  },
  {
    product: "shoes",
    name: "Thread Collect",
    link: "https://threadcollect.com.au/",
    location: "City of Port Phillip and surrounding suburbs",
    drop_off: "Collection",
    notes: "market days",
  },
  {
    product: "household items",
    name: "Thread Collect",
    link: "https://threadcollect.com.au/",
    location: "City of Port Phillip and surrounding suburbs",
    drop_off: "Collection",
    notes: "market days",
  },
  {
    product: "baby prams",
    name: "Thread Collect",
    link: "https://threadcollect.com.au/",
    location: "City of Port Phillip and surrounding suburbs",
    drop_off: "Collection",
    notes: "market days",
  },
  {
    product: "washing up liquid",
    name: "Soap Shop",
    link: "https://www.southmelbournemarket.com.au/traders/the-soap-shop",
    location: "South Melbourne Market",
    drop_off: "Wed, Fri, Sat and Sun",
    notes: "market days",
  },
  {
    product: "laundry detergent",
    name: "Soap Shop",
    link: "https://www.southmelbournemarket.com.au/traders/the-soap-shop",
    location: "South Melbourne Market",
    drop_off: "Wed, Fri, Sat and Sun",
    notes: "market days",
  },
  {
    product: "fabric softeners",
    name: "Soap Shop",
    link: "https://www.southmelbournemarket.com.au/traders/the-soap-shop",
    location: "South Melbourne Market",
    drop_off: "Wed, Fri, Sat and Sun",
    notes: "market days",
  },
  {
    product: "disinfectants",
    name: "Soap Shop",
    link: "https://www.southmelbournemarket.com.au/traders/the-soap-shop",
    location: "South Melbourne Market",
    drop_off: "Wed, Fri, Sat and Sun",
    notes: "market days",
  },
  {
    product: "shampoo",
    name: "Soap Shop",
    link: "https://www.southmelbournemarket.com.au/traders/the-soap-shop",
    location: "South Melbourne Market",
    drop_off: "Wed, Fri, Sat and Sun",
    notes: "market days",
  },
  {
    product: "conditioner",
    name: "Soap Shop",
    link: "https://www.southmelbournemarket.com.au/traders/the-soap-shop",
    location: "South Melbourne Market",
    drop_off: "Wed, Fri, Sat and Sun",
    notes: "market days",
  },
  {
    product: "body wash and more",
    name: "Soap Shop",
    link: "https://www.southmelbournemarket.com.au/traders/the-soap-shop",
    location: "South Melbourne Market",
    drop_off: "Wed, Fri, Sat and Sun",
    notes: "market days",
  },
  {
    product: "Soft plastics collection",
    name: "Recycle Smart",
    link: "https://www.recyclesmart.com/",
    location: "CoPP and some other council areas",
    drop_off: "Collection",
    notes: "",
  },
  {
    product: "Returnr cups for coffee and canisters for beans",
    name: "Market Lane Coffee",
    link: "https://marketlane.com.au/",
    location: "305 Coventry St, South Melbourne",
    drop_off: "Collection",
    notes: "7 days a week",
  },
];
export default data;
